### ISSUE TITLE
Doesn't show an understandable error when a column, etc is not found using SQL

### ISSUE THREAD

**Issue by aa7955** [IBM-Cloud/sql-query-clients#4]
Unintelligible message shows when a user writes an SQL statement and a column is not found. In the SQL UI, you will see something like:

<img width="770" alt="screen shot 2018-02-15 at 7 09 39 pm" src="https://user-images.githubusercontent.com/6264696/36292032-d146f630-1283-11e8-8507-9791f7737bc3.png">

Whereas the library will show:

<img width="746" alt="screen shot 2018-02-15 at 7 10 22 pm" src="https://user-images.githubusercontent.com/6264696/36292055-e787ad0e-1283-11e8-9474-840c88b83e86.png">

It should pass on the same error as the SQL UI I believe, which would make a better user/developer experience.

**Comment by aa7955** [comment]
I think I might have a crack at this since the message comes straight from the API.

**Comment by torsstei** [comment]
@aa7955 I've just fixed it. Yes, it was a matter of passing through the correct error message from the API. The above error happens during SQL execution and needs to be handled when checking the outcome in wait_for_job(). Another place where handling is needed is when the submission itself fails because the SQL has syntax errors. I put in handling for both now. Published in 0.2.4.

**Comment by aa7955** [comment]
That's still broken. It's exiting out of `wait_for_job` but `get_result` is still being executed and throwing an error. So when it doesn't get anything back, it still passes on the XML like:

```
b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>sql-e84e2979-43b2-4013-9002-15ec66b23daf</Name><Prefix>test/jobid=51d3c451-249c-486a-9689-18998bfde342/part</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>'
```

But since there are no contents, you get the error when `get_results` tries to get the results from COS.

**Comment by torsstei** [comment]
@aa7955 I cannot reproduce the problem. The error handling works correctly for me:

```
>>> print("Running test with SQL grammar error:")
Running test with SQL grammar error:
>>> sqlClient.run_sql("SELECT xyzFROM cos://us-geo/sql/employees.parquet STORED AS PARQUET LIMIT 10")
"SQL job submission failed. SQL submission failed: SQL syntax validation failed. Syntax error at line 1:15 mismatched input 'cos://us-geo/sql/employees.parquet' expecting <EOF>"
>>> 
>>> print("Running test with SQL runtime error:")
Running test with SQL runtime error:
>>> sqlClient.run_sql("SELECT xyz FROM cos://us-geo/sql/employees.parquet STORED AS PARQUET LIMIT 10")
Job 61f06265-2cbc-4055-9897-192ad0bb8e7f has failed
'SQL job 61f06265-2cbc-4055-9897-192ad0bb8e7f failed while executing with error SQL execution failed. Detailed message: A non-existing column used: xyz. Use an existing column.'
```

Can it be that you are using an outdated version. You should see
```
>>> import pkg_resources
>>> pkg_resources.get_distribution("ibmcloudsql").version
'0.2.4'
```

You can enforce an upgrade in notebook env using `!pip install --upgrade --force-reinstall ibmcloudsql`

**Comment by aa7955** [comment]
You have the exception check in `run_sql` and that's not the problem. The problem comes when you run the methods individually then try to `get_result`. That's when you get the problem like where ` "Victim Se AS sex \" is the error: 

```
sqlClient = ibmcloudsql.SQLQuery(cloud_api_key, sql_service_instance_id, sql_cos_endpoint)

sqlClient.logon()

traffic = sqlClient.submit_sql(
"SELECT \
    `Time Occurred` AS time, \
    `Area Name` AS area, \
    `Victim Age` AS age, \
    `Victim Se` AS sex \
FROM cos://us-south/data-storage/Traffic_Collision_Data_from_2010_to_Present.csv STORED AS CSV \
WHERE \
    `Time Occurred` >= 1800 AND `Time Occurred` <= 2000 AND \
    `Victim Age` >= 30 AND `Victim Age` <= 35 AND `Area Name` = 'Topanga' ")

sqlClient.wait_for_job(traffic)
sqlClient.get_result(traffic)
```

**Comment by torsstei** [comment]
Alright @aa7955, your are correct. I've fixed that now in get_result() and delete_result(). These methods now raise a ValueError when being called for a jobId without status `completed`. Published in v0.2.5.

Thanks!
